# Generated by Django 5.1.4 on 2024-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.CharField(default='No content provided', max_length=280),
        ),
    ]
