# Generated by Django 5.1.4 on 2024-12-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
    ]
